name: iCarry Tracking Scraper

on:
  schedule:
    - cron: "38 * * * *"
  workflow_dispatch:
    inputs:
      tracking_number:
        description: 'Tracking number to scrape'
        required: true
        default: '347720741487'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    
    - name: Install Chrome and Xvfb
      run: |
        sudo apt update
        sudo apt install -y xvfb fonts-liberation libasound2 libatk-bridge2.0-0 libatspi2.0-0 libdrm2 libgbm1 libgtk-3-0 libnspr4 libnss3 libu2f-udev libvulkan1 libxcomposite1 libxdamage1 libxfixes3 libxkbcommon0 libxrandr2 xdg-utils
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        sudo apt install -y -f
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install seleniumbase>=4.22.5
        pip install cloudscraper
    
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
        
    - name: Start Xvfb
      run: |
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        echo "DISPLAY=:99.0" >> $GITHUB_ENV
        
    - name: Create script
      run: |
        cat > scrape_tracking.py << 'EOL'
        from seleniumbase import Driver
        from selenium.webdriver.common.by import By
        from selenium.webdriver.support.ui import WebDriverWait
        from selenium.webdriver.support import expected_conditions as EC
        import time
        import os
        import argparse
        from datetime import datetime, timezone

        def get_current_utc():
            return datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%SS')

        def main():
            parser = argparse.ArgumentParser()
            parser.add_argument('--debug', action='store_true')
            args = parser.parse_args()
            
            print(f"Current Date and Time (UTC): {get_current_utc()}")
            print(f"Current User's Login: {os.getenv('GITHUB_ACTOR', 'KoolPal')}")
            
            tracking_number = os.getenv('TRACKING_NUMBER', '347720741487')
            url = f"https://www.icarry.in/track-shipment?a={tracking_number}"
            
            if args.debug:
                print("Creating driver...")
            
            driver = Driver(
                uc=True,
                headed=False,
                agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.5615.138 Safari/537.36",
                block_images=True,
                mobile=False,
                chromium_arg="--no-sandbox"
            )
            
            try:
                if args.debug:
                    print(f"Navigating to {url}")
                
                driver.get(url)
                
                if args.debug:
                    print("Waiting for page load...")
                
                time.sleep(20)
                
                if args.debug:
                    print("Getting page source...")
                
                content = driver.page_source
                print("\nPage content preview:")
                print(content[:500])
                
            except Exception as e:
                print(f"Error: {str(e)}")
                raise
            
            finally:
                if args.debug:
                    print("Closing driver...")
                driver.quit()

        if __name__ == "__main__":
            main()
        EOL

    - name: Run scraper
      env:
        DISPLAY: ":99.0"
        TRACKING_NUMBER: ${{ github.event.inputs.tracking_number || '347720741487' }}
      run: |
        python -u scrape_tracking.py --debug
