name: iCarry Tracking Scraper

on:
  workflow_dispatch:
    inputs:
      tracking_number:
        description: 'Tracking number to scrape'
        required: true
        default: '347720741487'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install seleniumbase>=4.22.5
        pip install undetected-chromedriver
        pip install cloudscraper

    - name: Create script
      run: |
        cat > scraper.py << 'EOL'
        from seleniumbase import Driver
        from datetime import datetime, timezone
        import time
        import os
        import argparse

        def get_current_utc():
            return datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')

        def main():
            parser = argparse.ArgumentParser()
            parser.add_argument('--debug', action='store_true')
            args = parser.parse_args()

            print(f"Current Date and Time (UTC - YYYY-MM-DD HH:MM:SS formatted): {get_current_utc()}")
            print(f"Current User's Login: {os.getenv('GITHUB_ACTOR', 'KoolPal')}")

            tracking_number = os.getenv('TRACKING_NUMBER', '347720741487')
            url = f"https://www.icarry.in/track-shipment?a={tracking_number}"
            
            driver = Driver(
                uc=True,
                undetectable=True,
                headless2=False
            )

            try:
                driver.get(url)
                time.sleep(20)
                print(driver.page_source)
            finally:
                driver.quit()

        if __name__ == "__main__":
            main()
        EOL

    - name: Run scraper
      run: |
        python scraper.py --debug
      env:
        TRACKING_NUMBER: ${{ github.event.inputs.tracking_number || '347720741487' }}
