name: iCarry Tracking Scraper

on:
  workflow_dispatch:
    inputs:
      tracking_number:
        description: 'Tracking number to scrape'
        required: true
        default: '347720741487'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pip
        pip install --upgrade wheel
        pip install seleniumbase>=4.22.5
        pip install --upgrade pyautogui
        pip install --upgrade python-xlib
        pip install undetected-chromedriver

    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable

    - name: Check the console scripts interface
      run: |
        seleniumbase
        sbase

    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver

    - name: Make sure pytest is working
      run: |
        echo "def test_1(): pass" > nothing.py
        pytest nothing.py --uc

    - name: Create script
      run: |
        cat > scraper.py << 'EOL'
        from seleniumbase import Driver
        import time
        import os

        driver = Driver(
            browser="chrome",
            uc=True,
            headless2=False,
            incognito=True,
            agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.5615.138 Safari/537.36 AVG/112.0.21002.139",
            do_not_track=True,
            undetectable=True
        )

        tracking_number = os.getenv('TRACKING_NUMBER', '347720741487')
        url = f"https://www.icarry.in/track-shipment?a={tracking_number}"

        try:
            driver.get(url)
            time.sleep(20)
            print(driver.page_source)
        finally:
            driver.quit()
        EOL

    - name: Run scraper
      run: |
        python scraper.py
      env:
        TRACKING_NUMBER: ${{ github.event.inputs.tracking_number || '347720741487' }}
